name: communityconnect
region: us

services:
  - name: web
    github:
      repo: your-username/CommunityConnect
      branch: main
      deploy_on_push: true
    build_command: npm install && npm run build
    run_command: npm start
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      # Add other environment variables in DigitalOcean dashboard
      # VITE_FIREBASE_API_KEY
      # VITE_FIREBASE_PROJECT_ID
      # etc.





